Improve error reporting
While cdp Runtime.exceptionThrown reports errors it does so in a machine
readable, not humanreadable way. Let's print he stack ourselves using
window.onerror [1] to get pretty output [2]. Not sure if this really catches
everything so I'll keep the devtools subscription in just in case. We're
returning true because that should stop propagation [3] and we don't want the
ugly Runtime.exceptionThrown if we don't absolutely need it.

[1] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror
[2]
Compare
```
ReferenceError: udtrianedu is not defined
    at http://localhost:44487/test/index.mjs:6:1
```

To

```
unexpected error: {
  "exceptionDetails": {
    "columnNumber": 0,
    "exception": {
      "className": "ReferenceError",
      "description": "ReferenceError: udtrianedu is not defined\n    at http://localhost:44487/test/index.mjs:3:1",
      "objectId": "{\"injectedScriptId\":2,\"id\":1}",
      "preview": {
        "description": "ReferenceError: udtrianedu is not defined\n    at http://localhost:44487/test/index.mjs:3:1",
        "overflow": false,
        "properties": [
          {
            "name": "stack",
            "type": "string",
            "value": "ReferenceError: udtrianedu is not defined\n    at http://localhost:44487/test/index.mjs:3:1"
          },
          {
            "name": "message",
            "type": "string",
            "value": "udtrianedu is not defined"
          }
        ],
        "subtype": "error",
        "type": "object"
      },
      "subtype": "error",
      "type": "object"
    },
    "exceptionId": 1,
    "executionContextId": 2,
    "lineNumber": 2,
    "stackTrace": {
      "callFrames": [
        {
          "columnNumber": 0,
          "functionName": "",
          "lineNumber": 2,
          "scriptId": "5",
          "url": "http://localhost:44487/test/index.mjs"
        }
      ]
    },
    "text": "Uncaught",
    "url": "http://localhost:44487/test/index.mjs"
  },
  "timestamp": 1606427768257.3198
}
```

[3]
> When the function returns true, this prevents the firing of the default event handler.
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror